services:
  traefik:
    image: traefik:v3
    container_name: museum-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/data
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=kertu.beljaev@ametikool.ee
      - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https

  mysql:
    image: mysql:8.0
    container_name: museum-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: RootPass#2025
      MYSQL_DATABASE: museum_db
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_estonian_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  frontend:
    build:
      context: ./museum-frontend
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.frontend.rule: "Host(`ristematalu.duckdns.org`)"
      traefik.http.routers.frontend.entrypoints: "websecure"
      traefik.http.routers.frontend.priority: "1"
      traefik.http.routers.frontend.tls.certresolver: "letsencrypt"
      traefik.http.services.frontend.loadbalancer.server.port: "80"

  api:
    build:
      context: ./museum-api
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      API_DB_HOST: mysql
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: "Host(`ristematalu.duckdns.org`) && PathPrefix(`/api`)"
      traefik.http.routers.api.priority: "10"
      traefik.http.routers.api.entrypoints: "websecure"
      traefik.http.routers.api.tls.certresolver: "letsencrypt"
      traefik.http.services.api.loadbalancer.server.port: "8080"

volumes:
  mysql_data:
  traefik_data: